-- V05: receipts, the digital confirmation an accepted match produces (FR-07).
-- Brief section 3.2 "Acceptance/Receipt": Contract ID, match ID, decision, actor,
-- timestamp, IP/user-agent (or mock).

CREATE TABLE receipts (
    id          UUID PRIMARY KEY DEFAULT uuidv7(),
    -- A human-readable reference the parties can quote, distinct from the internal id.
    -- Generated by the database so no two receipts can share one even if two requests
    -- are handled at the same instant.
    contract_id TEXT NOT NULL UNIQUE
                DEFAULT 'TAMP-' || to_char(now(), 'YYYY') || '-'
                        || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10)),
    -- UNIQUE, not merely a reference: one agreement yields exactly one receipt. Enforcing
    -- it here rather than with a check-then-insert in #14 closes the race where two
    -- concurrent requests both find no receipt and both write one.
    match_id    UUID NOT NULL UNIQUE REFERENCES matches (id),
    decision    TEXT NOT NULL CHECK (decision IN ('ACCEPTED', 'REJECTED')),
    actor_id    UUID NOT NULL REFERENCES users (id),
    -- "where available" in the brief: absence is valid data, so these stay nullable
    -- rather than being defaulted to a placeholder that looks like a real value.
    ip_address  INET,
    user_agent  TEXT,
    issued_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE receipts IS
    'One immutable confirmation per decided match. contract_id is the reference quoted to users.';
