package za.co.ice.tamp.backend.acceptance;

import java.time.OffsetDateTime;
import java.util.UUID;
import za.co.ice.tamp.backend.persistence.entity.Receipt;

/**
 * The digital confirmation issued on acceptance. {@code contractId} is the human-readable
 * reference the parties quote, distinct from the internal id and generated by the database.
 */
public record ReceiptResponse(
        UUID id,
        String contractId,
        UUID matchId,
        String decision,
        UUID actorId,
        String ipAddress,
        String userAgent,
        OffsetDateTime issuedAt) {

    public static ReceiptResponse from(Receipt receipt) {
        return new ReceiptResponse(
                receipt.getId(),
                receipt.getContractId(),
                receipt.getMatchId(),
                receipt.getDecision(),
                receipt.getActorId(),
                receipt.getIpAddress(),
                receipt.getUserAgent(),
                receipt.getIssuedAt());
    }
}
