package za.co.ice.tamp.backend.acceptance;

import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.Matchers.startsWith;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import za.co.ice.tamp.backend.MatchFixture;
import za.co.ice.tamp.backend.persistence.JpaTestBase;
import za.co.ice.tamp.backend.persistence.entity.Match;
import za.co.ice.tamp.backend.persistence.entity.User;
import za.co.ice.tamp.backend.persistence.repository.ReceiptRepository;

/**
 * FR-07: an accepted match produces a retrievable digital confirmation receipt.
 *
 * <p>Carries #14's Minimum Integration Test: accept a match via the API, then fetch the
 * resulting receipt and confirm it names the right match and actor.
 */
@AutoConfigureMockMvc
class ReceiptTest extends JpaTestBase {

    @Autowired
    private MockMvc mockMvc;
    @Autowired
    private MatchFixture fixture;
    @Autowired
    private ReceiptRepository receipts;

    @Test
    void acceptingAMatchProducesARetrievableReceipt() throws Exception {
        User owner = fixture.owner("rc-owner1@example.com");
        Match match = fixture.proposedMatch(owner, "rc-transporter1@example.com");

        mockMvc.perform(post("/matches/{id}/decision", match.getId())
                        .contentType(MediaType.APPLICATION_JSON)
                        .header("User-Agent", "tamp-demo-client/1.0")
                        .content(decision("ACCEPTED", owner)))
                .andExpect(status().isOk());

        mockMvc.perform(get("/matches/{id}/receipt", match.getId()))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.matchId").value(match.getId().toString()))
                .andExpect(jsonPath("$.actorId").value(owner.getId().toString()))
                .andExpect(jsonPath("$.decision").value("ACCEPTED"))
                .andExpect(jsonPath("$.issuedAt").isNotEmpty())
                // The brief's acceptance/receipt row asks for IP and user-agent "where
                // available". They are available on a real request, so not capturing them
                // would be discarding data the receipt is specified to carry.
                .andExpect(jsonPath("$.userAgent").value("tamp-demo-client/1.0"))
                .andExpect(jsonPath("$.ipAddress").isNotEmpty())
                // Generated by the database, so a null here means the entity was returned
                // straight from the persistence context without re-reading the insert.
                .andExpect(jsonPath("$.contractId").value(startsWith("TAMP-")));
    }

    @Test
    void rejectingAMatchProducesNoReceipt() throws Exception {
        // FR-07 is specifically "accepted match produces a receipt". The schema permits a
        // REJECTED receipt so #16's disputes can reference one later, but issuing a
        // "confirmation" for a refusal would misrepresent what happened.
        User owner = fixture.owner("rc-owner2@example.com");
        Match match = fixture.proposedMatch(owner, "rc-transporter2@example.com");

        mockMvc.perform(post("/matches/{id}/decision", match.getId())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(decision("REJECTED", owner)))
                .andExpect(status().isOk());

        assertThat(receipts.findByMatchId(match.getId())).isEmpty();

        mockMvc.perform(get("/matches/{id}/receipt", match.getId()))
                .andExpect(status().isNotFound());
    }

    private String decision(String decision, User actor) {
        return "{\"decision\": \"" + decision + "\", \"actorId\": \"" + actor.getId() + "\"}";
    }
}
