package za.co.ice.tamp.backend.tracking;

import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;
import org.springframework.stereotype.Service;
import za.co.ice.tamp.backend.acceptance.MatchNotFoundException;
import za.co.ice.tamp.backend.persistence.entity.Match;
import za.co.ice.tamp.backend.persistence.entity.MatchStatus;
import za.co.ice.tamp.backend.persistence.entity.TrackingEvent;
import za.co.ice.tamp.backend.persistence.repository.MatchRepository;
import za.co.ice.tamp.backend.persistence.repository.TrackingEventRepository;

/**
 * FR-08: records and returns simulated trip progress for an accepted match.
 *
 * <p>Reuses {@link MatchNotFoundException} from the acceptance package rather than declaring
 * a second exception meaning the same thing. The package dependency runs the right way round:
 * a trip only exists because a match was accepted, so tracking genuinely depends on
 * acceptance, and #9's future global error handler then has one type to map rather than two.
 */
@Service
public class TrackingCoordinator {

    private final MatchRepository matches;
    private final TrackingEventRepository events;

    public TrackingCoordinator(MatchRepository matches, TrackingEventRepository events) {
        this.matches = matches;
        this.events = events;
    }

    /**
     * Deliberately not {@code @Transactional}: the save and the read-back run as two
     * transactions on purpose, because {@code occurred_at} is generated by the database and
     * Hibernate never re-reads a generated default into the persistence context that inserted
     * the row. A single transaction would return an event with a null timestamp.
     */
    public TrackingEvent record(
            UUID matchId, String status, BigDecimal latitude, BigDecimal longitude) {
        Match match = matches.findById(matchId)
                .orElseThrow(() -> new MatchNotFoundException(matchId));

        if (!MatchStatus.ACCEPTED.equals(match.getStatus())) {
            throw new MatchNotAcceptedException(matchId, match.getStatus());
        }

        TrackingEvent saved = events.save(new TrackingEvent(matchId, latitude, longitude, status));
        return events.findById(saved.getId()).orElseThrow();
    }

    public List<TrackingEvent> historyFor(UUID matchId) {
        if (!matches.existsById(matchId)) {
            throw new MatchNotFoundException(matchId);
        }
        return events.findByMatchIdOrderByOccurredAtAsc(matchId);
    }
}
