package za.co.ice.tamp.backend.tracking;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import za.co.ice.tamp.backend.MatchFixture;
import za.co.ice.tamp.backend.persistence.JpaTestBase;
import za.co.ice.tamp.backend.persistence.entity.Match;
import za.co.ice.tamp.backend.persistence.entity.User;

/**
 * FR-08: an accepted match can be advanced through mock trip stages and read back.
 *
 * <p>Carries #15's Minimum Integration Test: advance a match's tracking status via the API,
 * then fetch it back and confirm the update persisted, in order.
 */
@AutoConfigureMockMvc
class TrackingTest extends JpaTestBase {

    @Autowired
    private MockMvc mockMvc;
    @Autowired
    private MatchFixture fixture;

    @Test
    void advancesAndReadsBackTrackingStatusInOrder() throws Exception {
        Match match = acceptedMatch("tk-owner1@example.com", "tk-transporter1@example.com");

        mockMvc.perform(post("/matches/{id}/tracking", match.getId())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"status\": \"IN_TRANSIT\"}"))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.status").value("IN_TRANSIT"))
                // Generated by the database. A null here means the response was built from
                // the in-memory entity, which never sees a column it did not insert.
                .andExpect(jsonPath("$.occurredAt").isNotEmpty());

        mockMvc.perform(post("/matches/{id}/tracking", match.getId())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"status\": \"DELIVERED\", "
                                + "\"latitude\": -29.858680, \"longitude\": 31.021840}"))
                .andExpect(status().isCreated());

        // Oldest first, so a trip reads as a progression. Insertion order and time order
        // agree here only because each POST is its own transaction; asserting the order
        // explicitly is what would catch a later switch to an unordered finder.
        mockMvc.perform(get("/matches/{id}/tracking", match.getId()))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.length()").value(2))
                .andExpect(jsonPath("$[0].status").value("IN_TRANSIT"))
                .andExpect(jsonPath("$[1].status").value("DELIVERED"))
                .andExpect(jsonPath("$[1].latitude").value(-29.858680))
                .andExpect(jsonPath("$[1].longitude").value(31.021840));
    }

    @Test
    void rejectsTrackingOnAMatchThatWasNeverAccepted() throws Exception {
        // The brief scopes tracking to "an accepted match". A CHECK constraint cannot read
        // another table, so nothing but this guard stops a trip being logged against a
        // proposal nobody agreed to. known-limitations.md assigned this rule to #15 by name.
        User owner = fixture.owner("tk-owner2@example.com");
        Match match = fixture.proposedMatch(owner, "tk-transporter2@example.com");

        mockMvc.perform(post("/matches/{id}/tracking", match.getId())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"status\": \"IN_TRANSIT\"}"))
                .andExpect(status().isConflict());
    }

    @Test
    void rejectsATrackingStatusTheSchemaWouldRefuse() throws Exception {
        Match match = acceptedMatch("tk-owner3@example.com", "tk-transporter3@example.com");

        mockMvc.perform(post("/matches/{id}/tracking", match.getId())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"status\": \"TELEPORTED\"}"))
                .andExpect(status().isBadRequest());
    }

    @Test
    void returns404ForTrackingOnAMatchThatDoesNotExist() throws Exception {
        mockMvc.perform(get("/matches/{id}/tracking", UUID.randomUUID()))
                .andExpect(status().isNotFound());
    }

    private Match acceptedMatch(String ownerEmail, String transporterEmail) throws Exception {
        User owner = fixture.owner(ownerEmail);
        Match match = fixture.proposedMatch(owner, transporterEmail);
        mockMvc.perform(post("/matches/{id}/decision", match.getId())
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"decision\": \"ACCEPTED\", \"actorId\": \""
                                + owner.getId() + "\"}"))
                .andExpect(status().isOk());
        return match;
    }
}
